### ISSUE TITLE
Remove / change `Delete Chunks` features.

### ISSUE THREAD

**Issue by ThatRedox** [chunky-dev/chunky#1034]
Currently it is too easy to accidently hit the `Delete Chunks` button and delete chunks. It should be either harder to accidently delete chunks or the feature should be removed altogether.

**Comment by jackjt8** [comment]
While this feature does get used extensively to prune chunks when updating world's; given the shift of chunky since rendering became it's focus and all the changes made since 2.0 removing this feature would be best.

If not with 2.4 but 2.5.

**Comment by ShirleyNekoDev** [comment]
I often use this feature but agree that its current implementation isn't ideal and may not be in line with the current chunky use-case and UI. Maybe we can split chunk operations (delete, export in zip, top-down map png export) into a separate plugin and make the internal API open for that.

**Comment by NotStirred** [comment]
allowing plugins to do whatever they want to a user's world is concerning. I suppose it is up to the user to verify that...
perhaps some warning if a plugin tries to modify your world? with an option to not allow it, or is it fine without?

**Comment by NotStirred** [comment]
Some form of "Danger Zone" would be nice, for any operations that modify the world

**Comment by ShirleyNekoDev** [comment]
> allowing plugins to do whatever they want to a user's world is concerning. I suppose it is up to the user to verify that...
> perhaps some warning if a plugin tries to modify your world? with an option to not allow it, or is it fine without?

Theoretically a plugin can currenlty modify any file on the system. I agree that the API could request user permission for that. Otherwise/additionally the API could ask to create a backup before doing write-operations on the world.

Danger Zone sounds good too, but I dislike the current UI panel on the right - it is pretty crowded with somewhat random/additional functionality. Maybe add this as a tab which is initially hidden and can be enabled via checkbox in the top menu?
