### ISSUE TITLE
Fog limited accuracy

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1268]
The Fog Slider only allows 0.0, 0.01 < x < 1.0 (max 2dp).

This provides limited accuracy. If possible we should at least allow 0.001 as the lower bounds of the slider.

The Fog Field has a 3dp limit (ie 0.001). Numbers like 0.0005 are rounded to 0.0 (not sure if it's just UI or internal).

**Comment by NotStirred** [comment]
This affects every floating point input box in chunky

I've tracked this down to us refreshing the input box with a user-readable double string, (rather than have a real double representation which isn't an option).

We could disable the refreshing, though that means it might be possible for the input box to be out of sync with the value we have stored. (Have tested and it seems ok so far)

**Comment by NotStirred** [comment]
Thinking about it, wouldn't it make more sense to refresh the value from the input box, that makes way more sense from the user's POV

**Comment by jackjt8** [comment]
I believe refreshing from input box was added as most user's expect it to work like that. The previous method, where you needed to press enter, was extremely confusing for users.
