### ISSUE TITLE
Add fields to set the position of entities

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [chunky-dev/chunky#1325]
Today I decided to make a render where our entire clan is in the maid costume. I stumbled upon a problem that has always annoyed me: models just can't be moved in XYZ. I would like this feature to be added in the future
![Screenshot_5471](https://user-images.githubusercontent.com/68144848/175464727-1f4d96aa-a20e-4ac6-a794-a88029978d91.png)
.

**Comment by Peregrine05** [comment]
One workaround is to use the camera to move the entity. The camera has XYZ controls, and it can be cloned.

Set the camera so that it is viewing the place where you want to position the camera. Clone the camera and then set the desired XYZ position of the entity in the camera controls. Click `Player to camera` in the Entities tab. Then return to the first camera to check the entity position. If it is not exactly where it is wanted, then return to the positioning camera, make an adjustment to its coordinates, then click `Player to camera`. Then view the results in the first camera.

**Comment by SPAWNRYS-ban** [comment]
> Set the camera so that it is viewing the place where you want to position the camera. Clone the camera and then set the desired XYZ position of the entity in the camera controls. Click `Player to camera` in the Entities tab. Then return to the first camera to check the entity position. If it is not exactly where it is wanted, then return to the positioning camera, make an adjustment to its coordinates, then click `Player to camera`. Then view the results in the first camera.

A good idea, but personally I resorted to changing the scene file, because there are places where it will be difficult with the camera, because the coordinate I need is inside the block

**Comment by Peregrine05** [comment]
You can set the camera coordinates so that it is inside a block as well. Then click `Player to camera` to move the player there.

**Comment by SPAWNRYS-ban** [comment]
> You can set the camera coordinates so that it is inside a block as well. Then click `Player to camera` to move the player there.

okay

**Comment by leMaik** [comment]
We'll just add inputs for the position, and maybe a button to move an entity to the target block (right-click, set target).
