### ISSUE TITLE
Loading a scene but not switching to its world will cause chunks to be selected in the current one

### ISSUE THREAD

**Issue by NotStirred** [chunky-dev/chunky#1359]
If you load a scene without switching to the world associated with it, its selection is still applied. If the selection overlaps with empty chunks in the current world, you have an invalid selection

This is the original cause for #1345, as the invalid selection causes empty chunks to load, which have a `null` version

**Comment by leMaik** [comment]
Is this an issue in 2.4.x, too?

**Comment by NotStirred** [comment]
Yep, in both stable and stable snapshot

**Comment by Peregrine05** [comment]
I assume that this means that the previous "fix" was not actually a fix, but a workaround?

**Comment by NotStirred** [comment]
Yep, it prevents the crash but we're still trying to load empty chunks which isn't good

**Comment by leMaik** [comment]
I just stumbled over this again: Loading empty chunks is a thing in ChunkyMap, resulting in the very same issue. When you automatically load chunks, you can't really check if they are empty in advance. I know that loading empty chunks isn't great from an octree perspective, but it's nice for automatic camera placement and we should ensure that Chunky doesn't crash and burn when we do so.

The workaround thus is valid and I'll backport it to 2.4.4. The proper fix is of course great for GUI usage of Chunky because it can result in smaller octrees and fewer chunks being loaded.
