### ISSUE TITLE
Missed blue pixels on rendering scenes

### ISSUE THREAD

**Issue by luiz-otavio** [chunky-dev/chunky#1360]
After rendering few images with the default properties and canvas resolution `1200x1200`, alot of blue pixels are rendered into the scene. These things are variable too, since those pixels are on each scene.

![image](https://user-images.githubusercontent.com/65752397/178585817-a7575a5a-581a-49ea-9893-db758bfc2f59.png)

I'm using the same hardware from [here](https://github.com/chunky-dev/chunky/issues/1315)

**Comment by Peregrine05** [comment]
From what I have heard, Chunky does not function as well when using a large number of threads. A better method to achieve similar rendering speed is to render separate copies of the same scene using separate Chunky instances with the total number of desired rendering threads divided among them, using the `Render threads` control in the `Advanced` tab. Merge all render dumps in the end to get the final render with less noise using `Merge render dump` in the `Advanced` tab.

**Comment by luiz-otavio** [comment]
> From what I have heard, Chunky does not function as well when using a large number of threads. A better method to achieve similar rendering speed is to render separate copies of the same scene using separate Chunky instances with the total number of desired rendering threads divided among them, using the `Render threads` control in the `Advanced` tab. Merge all render dumps in the end on one of the Chunky instances to get the final render with less noise using the `Merge render dump` control in the `Advanced` tab.

Great. Since I'm using the chunky in the CLI mode inside a Docker container, maybe I can launch alot of them distributed to let them working together for any renders with the same dump. Also, how can I use those options from `merge render dump` in the CLI? I have already those files in my dedicated server, so I guess that I can use in the rendering step.

**Comment by jackjt8** [comment]
The number of threads is not the issue here. Others have tested Ryzen 9-5950x's on Windows/Linux and have not faced any issues like this and in some cases even 128 core systems works fine. Now the performance aspect of things is true. Chunky's scaling is not the best in the world and you'll probably get better performance working with ~6-10 threads per worker. The exact number of threads does vary a bit.

So we will probably need to look elsewhere to understand what is going on here.

1) Assuming that spawning multiple instances of Chunky with 1 thread works - would you be able to test using a different Java? Maybe outside of docker if possible. I'm not sure if that Docker based yorks:java-17 has any issues.

2) If you still get the same issue with multiple instances of Chunky... Any chance you can do some hardware tests? I figure memory testing will be enough but who knows.

**Comment by luiz-otavio** [comment]
This thread is dead for most than `2 months`, I will close it. Thanks for the help!
