### ISSUE TITLE
Torches do not look like emitting ones. Just light from this magic place, but torch is dark.

### ISSUE THREAD

**Issue by Jolyk** [chunky-dev/chunky#264]
I noticed that emitting torches are not real. They look like not emitting at all. I reduced exposure to see accurately and i see that head of torch, must be most bright place on picture, actually is not. The wall near the torch is much brighter. If wall is so bright, the torch must be much brighter, overburned, whitened. And with glow around - cropped brightness is distributed to near pixels.
I try to post images here. Dark torch - original. Bright torch - photoshoped.
![chunky bad torch](https://cloud.githubusercontent.com/assets/7764647/3199022/281bcd32-ed62-11e3-9940-3a632f100fce.jpg)

![chunky bad torch photoshoped](https://cloud.githubusercontent.com/assets/7764647/3199027/39fdd126-ed62-11e3-95e0-db084a8e7d05.jpg)

**Comment by leMaik** [comment]
This would be fixed by using an emission map, i.e. #751

**Comment by Jolyk** [comment]
Thank you.

**Comment by Peregrine05** [comment]
The torch looks dark compared to its surroundings because (assuming you did not change it) the default emittance level for torches, which is 50, is so great that the surroundings closest to the torch appear much brighter than the torch itself. Reducing the exposure made the torch look dark completely, and its surroundings still outshine it. Using an emission map will allow only the top of the torch to emit light, but will not solve the overbrightness of the surroundings due to the too high emittance setting for the torch. Reduce the emittance value of the torch to something like 1, and the torch will instead outshine its surroundings.

**Comment by leMaik** [comment]
> Using an emission map will allow only the top of the torch to emit light

@Peregrine05 Let's keep this open until we do have emission maps then :)

**Comment by Peregrine05** [comment]
@leMaik Emission maps are not the issue here, and there is another issue tracking PBR support (#751). The images in this issue are not everything. The issue creator stated that the area around the torch is much brighter than the torch itself. That is likely due to the default emittance value of *50*, which the issue creator probably did not change. The apparent brightness of emitters is constant, and only appears to change when the exposure is changed. By reducing the exposure, the apparent brightness of the torches was decreased enough to make the outshining of the torches by their immediate surroundings much more apparent. That is the issue here, and it can be solved by reducing the emittance value of torches. An emission map can allow only the head of the torch to emit light, but as the light emitted by the base of the torch is negligable, even with an emission map, the head of the torch will likely still be bright enough to cause its surroundings to outshine it at the default emittance value of *50*.

**Comment by leMaik** [comment]
I see... All right then. Somehow this became my placeholder issue for "torches need emittance maps".
