### ISSUE TITLE
Bloom from light emitters. 

### ISSUE THREAD

**Issue by NJDaeger** [chunky-dev/chunky#405]
I feel it would be a nice addition to chunky to see an adjustable bloom from light emitting objects. This would also help solve the issue of seeing the reflection of the sun in reflections by masking the sun with a nice bloom. The way im thinking of bloom is how the sun bloom works in SEUS shaders or something similar.

**Comment by empirebuilder1** [comment]
So essentially, "bloom" would be a fuzz-factor in the ray tracing engine that makes the scanned rays from the light source (sun) on objects with reflective surfaces (water, metal/gem blocks, etc) scatter towards the camera more while becoming full-light rays instead of taking on the color of the object they reflected off of.

I don't see it being *too* difficult to implement, but it will most likely be a 1.5 or 1.6 release project. Then again, I'm not actually a coder so I can't actually tell you the difficulty of creating anything in particular.  ¯\_(ツ)_/¯

**Comment by llbit** [comment]
Bloom is fairly simple to implement as a pixel shader, however Chunky does not have pixel shaders. It could still be implemented without too much work, and it would be a nice feature to have, but I think this is a low priority feature right now.

**Comment by NJDaeger** [comment]
Thats understandable, you have numerous other things that are way more important than this lol example being the api. But ay least you added the FR tag :D

**Comment by leMaik** [comment]
The API to add new post-processors (e.g. bloom) was added in #949, @aTom3333 has an opcoming [chunky-bloom-plugin](https://github.com/aTom3333/chunky-bloom-plugin) for Chunky 2.4.0 or later. So I'll close this as _won't fix_.
