### ISSUE TITLE
Chunky stops responding when loading chunks

### ISSUE THREAD

**Issue by NJDaeger** [chunky-dev/chunky#415]
When I load selected chunks, chunky stops responding, but still loads the chunks. I am unsure why it does that, and I don't know if you get the same error I do. The selection was about 8000 chunks and I know it was still loading the chunks because of the high CPU usage and the increasing amount of RAM it was taking. And another question, I've been wondering this for a while now, but why does chunky take up so much memory? For a selection of 8000 chunks, it's taking ~7Gb. I don't know anything on this subject, but wouldn't it make sense if the consumed memory were around the same size as the map size? Ex: if the map were 1 Gb shouldn't it allocate 1 Gb of memory? Thanks!

**Comment by llbit** [comment]
The user interface can become unresponsive when loading many chunks because the user interface code needs to read some information which the loading process is modifying. The loading process uses a lock to make sure that there are no read errors while it is modifying that data, and that makes the user interface seem to freeze. This is a bug I'm aware of but it's tricky to fix in a good way.

The amount of memory needed to store a full Minecraft map in memory is much more than what it takes on disk, that is because Minecraft stores all the chunks in an efficient compressed format. When Chunky renders a scene it can't use a highly compressed internal format for the map because then it would take a long time to trace rays through a chunk.

Chunky uses an octree representation for most of the chunk data which in fact does compress the chunks a fair bit, while still being quick for ray tracing. If you do some back-of-the-envelope calculations you can easily estimate the size it would take to store the chunks uncompressed. On average you need about 16 bits to store non-empty blocks, so just take the number of blocks times 2 and you get the number of bytes:

```
blocks per chunk = 16 * 16 * 128
size = 8000 * 16 * 16 * 128 * 2 = 524288000 bytes = 500 Mb
```

**Comment by llbit** [comment]
Actually, the more I think about it, it seems like it should be less than 7Gb for the octree. Each octree node would have to be more than 30 bytes to exceed 7Gb.

**Comment by llbit** [comment]
Anyway I consider the GUI freezing thing to be a bug that I want to fix, so I'm marking this as a bug.

**Comment by NJDaeger** [comment]
Oh, thank you for the explanation! Makes more sense to me now. And could it be because of the fact I have alot of entities in the area I'm loading? (Entities being itemframes, armorstands, painting, signs etc)
