### ISSUE TITLE
Too bright sky through transparent leaves

### ISSUE THREAD

**Issue by llbit** [chunky-dev/chunky#514]
When the sky light setting is increased above 1.0, transparent leaves get very bright spots. This only happens when the texture is not fully transparent - only if it is partially transparent.

The following render demonstrates the effect.

![1 11 22-1000](https://user-images.githubusercontent.com/2757386/52917335-751bc100-32ea-11e9-8457-691e349a772a.png)

This was rendered using a custom texture pack where the space between leaves is not completely transparent. Here is the exact same scene rendered with the same settings but using Minecraft 1.13.2 textures:

![1 11 22-1000](https://user-images.githubusercontent.com/2757386/52917418-87e2c580-32eb-11e9-92a1-fe203140c52f.png)

This bug may be affecting all objects with transparent textures.

**Comment by Stenodyon** [comment]
I looked into it and this happens because the sky doesn't return the same color for a direct hit and for an indirect hit. A direct hit is not affected by the sky light setting while an indirect hit is. When a ray intersects a fully transparent part of a leaf block (alpha = 0), it is actually not counted as a hit and the ray continues on and can hit the sky directly, but when parts of the leaves are transparent but not completely, it is considered a hit and the ray is transmitted through, hitting the sky "indirectly".

What's interesting is that commented-out line in the code used for direct hits : https://github.com/llbit/chunky/blob/573424f349117937bb5112ddb1418395286b00a5/chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java#L417
It seems making direct hits not scaled by the sky light setting was intentional, probably because the sky looked too bright otherwise? Unfortunately this poses a problem as there is an inconsistency between the amount of light hitting the camera and the amount of light hitting the scene. I don't know how this should be resolved, in my opinion there should be no color difference between direct and indirect sky hits but I don't know how that would affect artists.
