### ISSUE TITLE
Making the Water configurable

### ISSUE THREAD

**Issue by ngedwards998** [chunky-dev/chunky#628]
Would you be able to add a ui element to chunky that would enable you to change the height of the waves? Or how random they could be?

leMaik had asked me to create an issue on GitHub for this. As a reminder. ;)

Thanks,
Pylons

**Comment by MadDog443** [comment]
Just gonna updoot this, I've also noticed that the water can be a pain to mess because its either like glass or very wavy which makes getting good reflections on the water while still having some waves hard. Adding a slider for wavelength, amplitude, density, direction, and a randomness slider for each would probably be perfect.
