### ISSUE TITLE
Long Running render Crash

### ISSUE THREAD

**Issue by stormboomer** [chunky-dev/chunky#654]
When doing long time renders (2 Days or more) Chunky just hangs up and stops rendering. There is no error Message.

Analysing Heap dump pointed out that the render manager is hitting the Int Limit on the Atomic Integer that is used to provide a new Job id
![image](https://user-images.githubusercontent.com/25079531/88719082-02d81e80-d123-11ea-8f88-39b0687d8467.png)

This Issue is probably caused by this
https://github.com/chunky-dev/chunky/blob/af0d633f427c44ca41420a21ba8394534ff2174d/chunky/src/java/se/llbit/chunky/renderer/RenderManager.java#L360

I think we need something to "dequeue" not used Job IDs
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicInteger.html

**Comment by leMaik** [comment]
While `job` is high, it's not high enough to cause problems. But `lastJob` seems to have flipped to a negative number. This causes an infinite loop here:

https://github.com/chunky-dev/chunky/blob/af0d633f427c44ca41420a21ba8394534ff2174d/chunky/src/java/se/llbit/chunky/renderer/RenderManager.java#L363
Job is positive, so it will always be higher than `lastJob`.

This should be fixed by changing the Job IDs to long, allowing you to render about 2^32 frames before it will freeze. Even at 10 FPS, that would be about 13 years.
