### ISSUE TITLE
[2.2] Ray Depth change mid-render doesn't reset render

### ISSUE THREAD

**Issue by StanleyMines** [chunky-dev/chunky#696]
Changing any of the other settings that modify how the render looks throws up a textbox to ask about resetting the value or restarting the render. Changing ray depth does not ask to restart render even though it changes how a scene looks 

(ex: set to 2, enable emitters, emitter render type to all, start render. Later change ray depth to like 100. New paths rendered in scene are much brighter (in dark scenes).)

**Comment by jackjt8** [comment]
[This topic was raised on Discord 6 months ago where we determined this is not the behaviour we should see](https://discordapp.com/channels/541221265512464394/543090398671929344/698828505160351764) and we also tracked it back to being an intentional change made back in 2013 (#103).

Recommended that we finally revert this change such that changing the Ray Depth resets the render.
