### ISSUE TITLE
Error messages can be created behind the chunky window

### ISSUE THREAD

**Issue by ProNoob135** [chunky-dev/chunky#739]
Sometimes error messages are created behind the chunky window, which is problematic because it cannot be moved or interacted with while they are displayed. (especially when there is a large amount of them from loading specific worlds.)
A temporary solution could be an option to disable error pop-ups.

**Comment by blueplanet150** [comment]
Could you please describe a specific case where an error message is created behind the main window? Or could you please supply one of those worlds which produce many error messages? Then we can reproduce the bug.

**Comment by jackjt8** [comment]
Issue was first reported over on leMaik's fork prior to write access being given to leMaik over here.

https://github.com/leMaik/chunky/issues/6 - The issue is typically with `Unknown Item ID` & (upto 2x) `Unknown octree Implementation` Warnings for which a new Warning window is spawned for each Unknown. Given only one window can have active focus all other Warnings tend to be pushed behind the Chunky window, and while Warnings exist you cannot simply minimise the Chunky window, you instead need to switch windows via the taskbar or alt+tab to `Ok` each Warning one after another.

![image](https://user-images.githubusercontent.com/3740917/104610743-48aa8400-567c-11eb-8b91-42b2ecf879e4.png)

Fixing player skin downloads certainly reduced the number of Warnings that can occur however it didn't solve the underlying UI.

Example world (trimmed): [Etho's LP.zip](https://github.com/chunky-dev/chunky/files/5815302/Etho.s.LP.zip)

The Error Window handles this much better as all errors end up in one Window rather than multiple.
