### ISSUE TITLE
Parallel projection autofocus does not "focus"

### ISSUE THREAD

**Issue by ShirleyNekoDev** [chunky-dev/chunky#946]
The autofocus uses the camera position do find the subject distance between camera and the block which is in the center of the camera projection. Because parallel projection "offsets the height as horizontal movement" (at least that is the result, because parallel projection), the vertical distance part of the subject distance should probably be excluded from the focus calculations or something like that?

Auto-focussed render for standard projection with adjusted DoF:
![image](https://user-images.githubusercontent.com/16897056/118370648-f08f7a00-b5a8-11eb-945f-2e8f74da7258.png)

Auto-focussed render for parallel projection with adjusted DoF:
![image](https://user-images.githubusercontent.com/16897056/118370765-83c8af80-b5a9-11eb-850a-a0264dbb44c4.png)

Expected focussed parallel projection (by subtracting the camera y position from the subject distance):
![image](https://user-images.githubusercontent.com/16897056/118370936-56c8cc80-b5aa-11eb-90e6-75bb3b36afab.png)

**Comment by alexhliu** [comment]
The autofocus button calls `Scene.autoFocus()` which calls `Scene.traceTarget()`. This calls `Camera.getTargetDirection()` which is basically `Camera.calcViewRay(ray, 0, 0)`. I suspect due to some parallel projector changes, this is calculating the distance from the edge of the octree to your scene, rather than from the current camera positon to the scene.
