### ISSUE TITLE
Canvas size is reset to 400x400 when running in headless mode

### ISSUE THREAD

**Issue by TOGoS** [chunky-dev/chunky#97]
I copied a .cvf, .grass, .foliage, and .octree files to a rackspace server, ran chunky -render <scene name>.cvf.  The .cvf specified to render a 1600x800 image.  After the first dump on the server, the .cvf had been rewritten to canvas width and height = 400, and the output image was 400x400 pixels.

(I would look into this myself but I have some 'real work' I need to get to, hence trying to offload my chunky renders to Rackspace ;P)

**Comment by Peregrine05** [comment]
Is this still a bug in the latest versions of Chunky (2.4.3 Stable, 2.4.x Stable Snapshot, and 2.5.0 Snapshot)?

**Comment by TOGoS** [comment]
> Is this still a bug in the latest versions of Chunky (2.4.3 Stable, 2.4.x Stable Snapshot, and 2.5.0 Snapshot)?

Good question.  I don't have that Rackspace server anymore and haven't tried to do any headless Chunky renders for a while.  If it cannot be reproduced by anyone else, I wouldn't argue with closing the issue.

**Comment by Peregrine05** [comment]
The scene format has definitely been changed since then, as scenes no longer use .grass, .foliage, or .cvf files. People have also had success with headless rendering at resolutions other than 400x400. Furthermore, I am unable to connect to that server to retrieve the instructions to reproduce the bug.
