### ISSUE TITLE
Chunky on Java 16 (this is needed for Minecraft) does not work

### ISSUE THREAD

**Issue by MrKiller01** [chunky-dev/chunky#998]
Mojang did again a bold and stupid move in my opinion, they brought Minecraft 1.17 to us that depends on Java 16+
Chunky I use for deleting unused blocks in our worlds that can regenerate in the current version.
Mojang failed to give us a clear program/option/tool to upgrade our worlds from the first aquatic to the 1.17 version where the whole world looks and feels different.
Are they that stupid over there in the North? all those server owners who try to get their world a bit up to the newest version and then this happens, again, and again.... and so on.

Chunky clearly will not start the way it used to work in the java 1.16 environment, we surely would like to see if it did so that we can upgrade our huge worlds a little bit, I hope you understand our predicament and upgrade Chunky too as well....

Thanks

**Comment by jackjt8** [comment]
Chunky does function correctly using the Minecraft 1.17's openjdk version "16.0.1" 2021-04-20 runtime.

Please provide more information as to the issue you are facing. You may need to launch Chunky via the commandline, ie `D:\Games\MinecraftLauncher\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin\java.exe -jar D:\Programs\Chunky_293\chunkylauncher.jar --launcher` in order to fully debug what the issue may be.

Assuming you are using the latest Chunky launcher being v1.12.1 it should detect the most common issue which is missing JavaFX which would not be included past JDK 8 anyway and is separate. -- This issue is to be addressed with the release of Chunky 2.4.0 when we provide new Chunky installers which will package OpenJFX among other things.

**Comment by leMaik** [comment]
This is not a place for rants and swearing about Minecraft.

If you want to know how to get Chunky working with Java 11+, please check #523 and linked issues. We will provide pre-made installers with Chunky 2.4.0 and Chunky does in fact work with Java 1.16.

**Comment by MrKiller01** [comment]
It is not the point of following the instructions, but the downloading of openJFX (and Lord, why do they change things in this matter and not solve the problem with it if it did work before) and then??? I have tried to 'do' something with it, all I have tried failed in a positive result. Now I may be stupid, and I might hear you laughing, but this proves again my theory and I hope developers stop a little and rethink their steps before scatter us into an abyss.
To answer your question, I normally run ChunkyLauncher2.3.jar by simply clicking on it, Spigot 1.17, because that is what I use for our servers, did not run on the current JAVA.... We had version 8, and all of a sudden jumping to version 16 made me scratch behind my ears too, where are the intermediate versions gone? Fact is that simply starting Chunky.jar did not work anymore.

So the problem I face and still not able to solve for using Chunky in the manner it used to is blocked by JFX. I cannot solve it, and to be honest, I have a lot on my plate right now, have five servers to look after, this is an unwelcome visitor.

If you want to help me on this JFX problem, I am greatfull, and if not, I hope the update comes soon.
@Jackjt8, thanks for helping.

**Comment by MrKiller01** [comment]
> This is not a place for rants and swearing about Minecraft.
> 
> If you want to know how to get Chunky working with Java 11+, please check #523 and linked issues. We will provide pre-made installers with Chunky 2.4.0 and Chunky does in fact work with Java 16.

Dear fireman, I did not rant nor swear about Mojang, I just placed a FACT.
If you think they can not handle a little criticism in facts, then let them come to me, I do not think I made any bad words here...
Ps. and closing ones topic without explaining or consult is rude.

**Comment by leMaik** [comment]
The whole way you are takking about the devs and me in particular is completely inappropriate. I don't think any of us should have to deal with this in their spare time, sorry. 

I explained it in the first comment. Being rude is rude. Closing rude issues isn't.

**Comment by leMaik** [comment]
Reopening to solve your issue. But please focus in the issue, not the involved devs.

**Comment by jackjt8** [comment]
Download and extract the [OpenJFX Windows SDK](https://gluonhq.com/products/javafx/) to `C:\Program Files\` creating a folder `openjfx`. Folder structure as seen here: 
![image](https://user-images.githubusercontent.com/3740917/121803731-cb8b3700-cc3a-11eb-9fea-1837d4f07a8f.png).

To test / debug Chunky - Open notepad.exe, end the following

```
cd /d %~dp0
java -jar ChunkyLauncher.jar --launcher
pause
```

save as `Chunky.bat` and place it next to the ChunkyLauncher.jar. You may need to replace java with the path to Java 16's java.exe if it's not the system default. Otherwise double clicking on this `.bat` file should run Chunky and also provide you with any errors should they occur.

![image](https://user-images.githubusercontent.com/3740917/121803920-8d424780-cc3b-11eb-852c-a6668261f73a.png)

**Comment by MrKiller01** [comment]
I did not meant to rant on the devs of Chunky, in my opinion they made a very useful tool to make certain parts of our world's look better. If what I told is ranting, then it is address is Mojang.
Every progress should not be a disaster, software-wise, but it sure looks like Mojang hates that we use Spigot, Paper, Sponge or whatnot, because ever time they update, there is always one and more plugins that either partially or totally fails, crimping unknowing parts in the world's, damaging chunks of worse, keeps crashing servers.
Now I am doing this just for fun, keeping 5 servers running, but I am also always, and that is certainly no lie, cleaning up after every update, intact, that was why I called out for Chunky , to help me out a bit.
So, sir, do not mistake me please, I am good willing and not bashfull but simply trying to maintain those public playgrounds.
Again, I am sorry if I was too hard, this was absolutely not my goal, I just need a little bit of understanding and support, and some TLC 🤗
Thanks for listening,

**Comment by MrKiller01** [comment]
@jackjt8, hi, I tried your instructions to the letter. I got Chunky started, but when I wanted to move further with LAUNCH, it gave up on me...
This was the error produced:
Launch error:  C:\Program Files (x86)\Java\jre1.8.0_291\bin\java.exe -Xmx512m -Dchunky.home=D:\GAMES\Chunky --module-path "C:\Program Files\openjfx\lib" --add-modules javafx.controls,javafx.fxml -Dprism.order=sw -classpath D:\GAMES\Chunky\lib\chunky-core-2.0-beta6.jar;D:\GAMES\Chunky\lib\commons-math3-3.2.jar se.llbit.chunky.main.Chunky
Debug console: Unrecognized option: --module-path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I am not sure, but it looks like something is not starting to make a Virtual Java Machine, but my deeper knowledge is not of this era, more that of the past century. So I cannot solve this. 

If you don't mind asking you, is it ok if I wait for the update of Chunky? then I stop worrying about this, and you too.....

thanks so far for your help here, much appreciated....🤗

**Comment by MrKiller01** [comment]
-about chunky? that was actually the latest I could find.... but 32 bit java? OMG..... this is gonna be harder every time we want something new.... I uninstalled all java... because it needed a higher version..,....... I really don't get it.....
Thanks man for your help.

**Comment by MrKiller01** [comment]
Ok, I tried something, uninstalled from laptop java 8, the JDK (64bit) I left there and retried it.... Chunky is opening now..... So, im gonna test further... I was about to give up on this java cra.... you know....

**Comment by MrKiller01** [comment]
Just one thing, and I had in the very far past a nice overview of my world, yet now I see only red, when I zoom in the screen fills with stop sign shaped 1.12.....
Does this mean???

**Comment by jackjt8** [comment]
The world has chunks from Minecraft 1.12 and Chunky 2.0-2.3 can't read them due to world format changes.

Update to the [Chunky 2.4 snapshots by enabling download snapshots, double check the update site, and checking for updates](https://jackjt8.github.io/ChunkyGuide/docs/userinterface/chunkylauncher.html#advanced-settings)

**Comment by MrKiller01** [comment]
Got that....  Thanks....
